# -*- coding: utf-8 -*-
"""dav_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwbGXyN1cvPEKuxZqUE_xntrvdm_cZI4
"""

import numpy as np

x = np.arange(18, dtype=np.int64).reshape(3, 6)
x[1:, ::2] = 50
x

import pandas as pd

data=["shahid","bobby","shareef","ganesh","nayan"]

df=pd.Series(data)

print(df)

install.packages("dplyr")

library(dplyr)

mydata = read.csv("/content/sample_data/california_housing_train.csv")

sample_n(mydata,11)

sample_frac(mydata,0.0001)

"""# New Section"""

install.packages("readr")

library(readr)

library(readr)
hello <- read_csv("/content/sample_data/california_housing_test.csv",n_max = 10)
hello

spec(hello)